### ISSUE TITLE
Não gera as pastas

### ISSUE THREAD

**Issue by Coesta** [sthormio/clean-dart-cli#3]
Não está funcionando, seja a geração completa (`clean-dart gen layer complete /example`) ou apenas uma camada (`clean-dart gen layer domain /example`)

Quando executo qualquer um dos comandos, a única linha que é impressa no terminal é:
`################### Clean Dart CLI ###################`
Mas não retorna erro algum...

A versão instalada é: `Clean Dart CLI at 0.0.21+3`

Tentei executar tanto pelo terminal integrado do VS Code, como pelo Power Shell (em modo administrador tbm).
Tentei tbm executar a partir da pasta raiz do projeto, como tbm na pasta específica do módulo, e nada.

**Comment by pauloantonelli** [comment]
i have the same problem!

**Comment by nitoba** [comment]
Thanks for your report. We identified this problem and already was solved. Now just update to the new version 0.0.31

**Comment by pauloantonelli** [comment]
> Thanks for your report. We identified this problem and already was solved. Now just update to the new version 0.0.31

it work's thanks!!
